---
# - name: Hello World!
#   hosts: all
#
#   tasks:
#
#   - name: Hello World!
#     shell: echo "Hi! Tower is working."



- name: Ping linux server
  hosts: all
  gather_facts: false

  tasks:
  - name: Ping linux server
    ping:
